import "./globals.css";
import Providers from "./providers.js";
import DeepLinkHandler from "./DeepLinkHandler";

export const metadata = {
  title: "Android App",
  description: "Generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DeepLinkHandler />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
