import "./globals.css";

export const metadata = {
  title: "Android App",
  description: "Generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
